name: Rate Limiter Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    env:
      REDIS_URL: redis://localhost:6379
      
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          install-mode: goinstall

      - name: Download Modules
        run: go mod download

      - name: Run Tests
        run: go test -v -race ./...
        env:
          REDIS_URL: redis://localhost:6379